### ISSUE TITLE
Need alignment output

### ISSUE THREAD

**Issue by bkille** [InfOmics/PANPROVA#1]
Hi! Its great to see a new tool for simulation bacterial evolution. I'm looking to use PANPROVA for validating some alignment methods. While the different output files are indeed helpful, what I really need is a [`maf`](https://genome.ucsc.edu/FAQ/FAQformat.html#format5) file that contains the alignments of all of the sequences. 

Is this a pending feature for PANPROVA and if not, how would one go about reconstructing the nucleotide-level homologies across all of the simulated genomes?

**Comment by vbonnici** [comment]
Dear bkille,
currently, PANPROVA does not compute sequence alignment, thus no maf files are produced.
The file OPREFIX.gene_familes reports the composition of gene families. One family for each row.
Sequences of genes can be found in OPREFIX.genes.
Starting from these two files, one can compute multiple alignment for each gene family.

OPREFIX is the values of the parameter "-oprefix output_prefix"

I will write an example regarding this, asap.
However, since we want to reduce dependency on external tools, biopython will be used for the alignment, thus it will be slower than more efficient solutions.

Instead, if you need genome-level sequence similarity, example 6 is probably what you need. It does not compute alignment, still, but it uses the famous CVTree software for computing genome similarity by means of k-mers. The software outputs two-by-two similarities, on top of which a phylogenomic tree is reconstructed.

**Comment by vbonnici** [comment]
Dear bkille,
I have made test 7 to show how to obtain multiple sequence alignments of gene families.
Let me know if everything is fine.
